discounts-green:
  replicaCount: 1
  image:
    tag: "latest"

discountsNetworkingOnline:
   version: blue

discounts-blue:
  replicaCount: 2
  image:
    tag: "latest"

discountsNetworkingOffline:
   version: green

#Step1 Upgrade Discounts OffLine for testing
# discounts-green:
#   image:
#     tag: "v1"

#Step2 Scale up Discounts Offline (new version)
# discounts-green:
#   replicaCount: 2

#Step3 Switch Discounts new version to Online
# discountsNetworkingOnline:
#    version: green

#Step4 Discounts old version Scale down, aligne version and switch to OffLine
# discounts-blue:
#   replicaCount: 1
#   image:
#     tag: "v1"
# discountsNetworkingOffline:
#    version: blue