discountsNetworkingOnline:
  version: blue
discountsNetworkingOffline:
  version: green

productsNetworkingOnline:
  version: blue
  router:
    enabled: true
productsNetworkingOffline:
  version: green
  router:
    enabled: true

products-green:
  replicaCount: 1
  image:
    tag: "latest"
  discountsApi:
    #has to change when product on/offline change
    url: http://discounts-umbrella-offline:8080 
products-blue:
  replicaCount: 2
  image:
    tag: "latest"
  discountsApi:
    #has to change when product on/offline change
    url: http://discounts-umbrella-online:8080

discounts-green:
  replicaCount: 1
  image:
    tag: latest
discounts-blue:
  replicaCount: 2
  image:
    tag: "latest"

global:
  istio:
    enabled: false

