apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-discounts-scale-down-offline-
spec:
  pipelineRef:
    name: pipeline-blue-green    
  params:
  - name: APP
    value: discounts
  - name: NEW_IMAGE_TAG
    value: "v1"
  - name: STEP
    value: "scale-down-offline"
  - name: SOURCE_GIT_REVISION
    value: blue-green
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version