apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-discounts-switch-
spec:
  pipelineRef:
    name: new-version-quarkus-application    
  params:
  - name: APP
    value: discounts
  - name: NEW_IMAGE_TAG
    value: "v1"
  - name: REPLICA_COUNT
    value: "2"
  - name: STEP
    value: "switch"
  - name: SOURCE_GIT_REVISION
    value: blue-green
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version