apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-products-scale-up-
spec:
  pipelineRef:
    name: new-version-quarkus-application    
  params:
  - name: APP
    value: products
  - name: REPLICA_COUNT
    value: "2"
  - name: STEP
    value: "new-version-scale-up"
  - name: SOURCE_GIT_REVISION
    value: blue-green
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version