apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-discounts-scale-up-
spec:
  pipelineRef:
    name: new-version-quarkus-application    
  params:
  - name: APP
    value: discounts
  - name: REPLICA_COUNT
    value: "2"
  - name: STEP
    value: "new-version-scale-up"
  - name: SOURCE_GIT_REVISION
    value: istio
  - name: ISTIO
    value: "true"
  - name: VALUES_FILE
    value: istio/values-istio-canary.yaml 
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version