apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: shop-discounts-scale-down-offline-
spec:
  pipelineRef:
    name: new-version-quarkus-application    
  params:
  - name: APP
    value: discounts
  - name: NEW_IMAGE_TAG
    value: "v1"
  - name: STEP
    value: "scale-down-offline"
  - name: SOURCE_GIT_REVISION
    value: istio
  - name: ISTIO
    value: "true"
  - name: VALUES_FILE
    value: istio/values-istio-canary.yaml 
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: workspace-pvc-shop-cd-new-version