apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-quarkus-application
spec:
  params:
  - name: HELM_RELEASE_NAME
    type: string
    default: shop-blue-green
    description: The application deployment name
  - name: SOURCE_GIT_URL
    type: string
    default: https://github.com/davidseve/quarkus-helm-umbrella.git
    description: The application git repository url
  - name: SOURCE_GIT_REVISION
    type: string
    default: main
    description: The application git repository revision
  - name: CONTEXT_DIR
    type: string
    default: "chart-blue-green"
    description: The subdirectory in the git repository
  - name: HELM_RELEASE_VERSION
    type: string
    default: v1.0.0
    description: Helm release version
  - name: NAMESPACE
    type: string
    default: poc-quarkus
    description: namespace
  - name: OVERWRITE_VALUES
    type: string
    default: ""
  - name: VALUES_FILE
    type: string
    default: "no-istio/values-no-istio.yaml"   

  workspaces:
  - name: app-source

  tasks:
  - name: git-clone
    taskRef:
      kind: ClusterTask
      name: git-clone
    params:
    - name: url
      value: $(params.SOURCE_GIT_URL)
    - name: revision
      value: $(params.SOURCE_GIT_REVISION)
    - name: deleteExisting
      value: 'true'
    workspaces:
    - name: output
      workspace: app-source
  - name: helm-upgrade
    runAfter:
    - git-clone
    taskRef:
      name: helm-upgrade-from-source
    params:
    - name: charts_dir
      value: $(params.CONTEXT_DIR)
    - name: release_version
      value: $(params.HELM_RELEASE_VERSION)
    - name: release_name
      value: $(params.HELM_RELEASE_NAME)
    - name: release_namespace
      value: $(params.NAMESPACE)
    - name: overwrite_values
      value: $(params.OVERWRITE_VALUES)
    - name: values_file
      value: $(params.VALUES_FILE)
    workspaces:
    - name: source
      workspace: app-source
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc-shop-cd-install
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi