apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: delete-quarkus-application
spec:
  params:
  - name: HELM_RELEASE_NAME
    type: string
    default: shop-blue-green
    description: The application deployment name
  - name: NAMESPACE
    type: string
    default: poc-quarkus
    description: namespace

  tasks:


  - name: helm-upgrade
    runAfter:
    - create-result-colour
    taskRef:
      name: helm-upgrade-from-source
    params:
    - name: charts_dir
      value: $(params.CONTEXT_DIR)
    - name: release_version
      value: $(params.HELM_RELEASE_VERSION)
    - name: release_name
      value: $(params.HELM_RELEASE_NAME)
    - name: release_namespace
      value: $(params.NAMESPACE)
    - name: overwrite_values
      value: $(params.APP)-$(tasks.create-result-colour.results.version).image.tag=$(params.NEW_IMAGE_TAG)
    - name: values_file
      value: $(params.VALUES_FILE)
    workspaces:
    - name: source
      workspace: app-source
