apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shop-istio
spec:
  destination:
    name: ''
    namespace: quarkus-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: quarkus-helm-umbrella/chart-blue-green
    repoURL: 'https://github.com/davidseve/poc-quarkus-applications-helm.git'
    targetRevision: istio
    helm:
      valueFiles:
        - istio/values-istio-canary.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
