apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-cluster-configuration
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: quarkus-helm-umbrella/gitops/cluster-config
    repoURL: 'https://github.com/davidseve/poc-quarkus-applications-helm.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default